<?php
namespace Networkteam\Import\DataProvider;

/***************************************************************
 *  (c) 2014 networkteam GmbH - all rights reserved
 ***************************************************************/

use Networkteam\Import\Validation\RowValidationInterface;

/**
 * Class RowValidationDecorator
 * Will validate a row according to configured rowValidators. See example for "NotEmptyRowValidator"
 *
 */
class RowValidationDecorator extends BaseProviderDecorator
{

    const OPTION_SKIP_ON_EXCEPTION = 'row_validator.skip_on_exception';

    /**
     * @var array
     */
    protected $options = [
        self::OPTION_SKIP_ON_EXCEPTION => true
    ];

    /**
     * @var RowValidationInterface
     */
    protected $rowValidator;

    /**
     * @inheritdoc
     */
    public function current()
    {
        return $this->dataProvider->current();
    }

    /**
     * @return boolean
     */
    public function valid()
    {
        do {
            if ($this->dataProvider->valid() === false) {
                return false;
            }

            try {
                $currentRow = $this->dataProvider->current();
                $currentRowIsValid = $this->rowValidator->isValid($currentRow);
            } catch (\Exception $e) {
                if ($this->options[self::OPTION_SKIP_ON_EXCEPTION] === true) {
                    $currentRowIsValid = false;
                } else {
                    throw $e;
                }
            }

            if ($currentRowIsValid === false) {
                $this->dataProvider->next();
            }
        } while ($currentRowIsValid === false);

        return $currentRowIsValid;
    }

    /**
     * @param $rowValidator
     */
    public function setValidator($rowValidator)
    {
        $this->rowValidator = $rowValidator;
    }

    public function setOptions(array $options)
    {
        $this->options = array_merge($this->options, $options);
        parent::setOptions($options); // TODO: Change the autogenerated stub
    }
}
